services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nextjs_client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./client/.env.production
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge